### ISSUE TITLE
Task list with dates

### ISSUE THREAD

**Issue by pfarkya** [pfarkya/local-searcher#4]
here is the checklist for the task to be done 

- [x] profile page editable @pfarkya  due date 13/1/19
- [x] create profile page @pfarkya  due date 13/1/19
- [x] create enterprise page  @pfarkya  due date 13/1/19
- [ ] enterprise page @pfarkya  due date 13/1/19
- [x] enterprises list @pfarkya  due date 13/1/19
- [ ] product page @pfarkya  due date 23/1/19
- [x] account page @pfarkya  due date 23/1/19
- [x] search page @pfarkya due date 30/1/19
- [ ] beatification of pages Pawan due date 5/2/19

**Comment by pavankkus** [comment]
![profile](https://user-images.githubusercontent.com/23234451/51130415-f64ae880-1852-11e9-8637-80f550c5f863.jpg)

**Comment by pavankkus** [comment]
![products](https://user-images.githubusercontent.com/23234451/51130652-7b360200-1853-11e9-8cb1-76a7a9d148b6.jpg)

**Comment by pavankkus** [comment]
![image](https://user-images.githubusercontent.com/23234451/51131413-afaabd80-1855-11e9-8045-1fdb18699d77.png)

**Comment by pavankkus** [comment]
![image](https://user-images.githubusercontent.com/23234451/51425403-c78d9300-1c01-11e9-98b0-16654676a50e.png)
prashant please check this error, this error is coming while registering.
